# 1.3 Python Introduction

The material presented in this notebook is heavily based on the Datacamp "Introduction to Python for Data Science" course. Check the full course [here](https://app.datacamp.com/learn/courses/intro-to-python-for-data-science).

Python is a general-purpose programming language that is becoming ever more popular for data science (also used for web development, application development etc...). Companies worldwide are using Python to harvest insights from their data and gain a competitive edge. This notebook will focus particularly on an introduction to Python from a data science perspective. You will get to see powerful ways to store and manipulate data and learn about helpful tools to begin conducting your own analyses.

Python
- general purpose (build anything; swiss army knife)
- open source (free)
- Python ecosystem (packages for data science; community; easy to build new packages)

## Calculations

In [1]:
# Addition (hashtag indicates a comment)
print(1 + 2)

# Subtraction
print(2 - 1)

# Multiplication, division, modulo and exponentiation
print(3 * 5)
print(10 / 2)
print(18 % 7)
print(4 ** 2)

3
1
15
5.0
4
16


In [2]:
### TO DO ###
'''
Suppose you have $100 which you can invest with a 10% return each year.
Add code to calculate how much money you end up with after 7 years and print the result
'''

### SOLUTION ###
print(100 * 1.1 ** 7)

194.87171000000012


## Variables and Types

- Save values and call them up later
- Specific, case-sensitive name

In [3]:
height = 1.79
weight = 68.7
bmi = weight / height ** 2
print(bmi)

21.44127836209856


In [4]:
# Floats
print(type(bmi))

<class 'float'>


In [5]:
# Integers
day_of_week = 5
print(type(day_of_week))
print(2 + 3)

<class 'int'>
5


In [6]:
# Strings
x = "body mass index"
y = "abc"
print(type(x))
print(x + y) # operator action depends on data type

<class 'str'>
body mass indexabc


In [7]:
# Booleans
z = True
print(type(z))

<class 'bool'>


In [8]:
# Type conversion
print("The body mass index is " + str(bmi) + "!")

pi_string = "3.1415926"
pi_float = float(pi_string)
pi_int = int(pi_float)
pi_bool = bool(pi_int)
print(pi_string)
print(pi_float)
print(pi_int)
print(pi_bool)

The body mass index is 21.44127836209856!
3.1415926
3.1415926
3
True


In [9]:
print("I can add integers, like " + str(5) + " to strings.")

I can add integers, like 5 to strings.


In [10]:
print("I said " + ("Hey " * 2) + "Hey!")

I said Hey Hey Hey!


In [11]:
print("Can I add an integer like this to a string " + 5) # this will throw an error

TypeError: can only concatenate str (not "int") to str

In [12]:
print(True + False + True)

2


In [13]:
### TO DO ###
'''
Create a variable called "savings" with the value 100 and print it.
Create a variable called "growth_multiplier" with the value 1.1.
Use "savings" and "growth multiplier" to do the same calculation that you did in the previous to do
and store the result in a variable called "result".
Print out the result.
Create a new string called "desc" with the value "compound interest".
Create a new boolean called "profitable" with the value True.
Print out the type of the "savings" and "growth_multiplier" variables.
'''

### SOLUTION ###
savings = 100
print(savings)
growth_multiplier = 1.1
result = savings * growth_multiplier ** 7
print(result)
desc = "compound interest"
profitable = True
print(type(savings))
print(type(growth_multiplier))

100
194.87171000000012
<class 'int'>
<class 'float'>


## Lists

- Work with many data points -> store in list
- Give a single name to collection of values
- Mixed data types possible (even nested lists)
- List is a data type with specific functionality and behavior

In [14]:
fam = [1.73, 1.68, 1.71, 1.89]

In [15]:
fam2 = [["liz", 1.73],
        ["emma", 1.68],
        ["mom", 1.71],
        ["dad", 1.89]]

In [16]:
print(type(fam))

<class 'list'>


In [17]:
print(type(fam2))

<class 'list'>


In [18]:
### TO DO ###
'''
Create a list called "areas" and store the area sizes of the following rooms in it
in this order: hallway (11.25), kitchen (18.0), living room (20.0), bedroom (10.75), bathroom (9.50).
Print the list "areas".
Now create a list called "areas_mixed" with mixed data types by adding the room name as string before
the area sizes respectively.
Print the list "areas_mixed".
Next create a list of lists called "house" with each room name and area size in a seperate list.
Print the list "house".
'''

### SOLUTION ###
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50
areas = [hall, kit, liv, bed, bath]
print(areas)
areas_mixed = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]
print(areas_mixed)
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom",bed],
         ["bathroom",bath]]
print(house)

[11.25, 18.0, 20.0, 10.75, 9.5]
['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]
[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]


In [19]:
# Subsetting lists
print(fam[0]) # 0-indexing
print(fam[-1])

# List slicing
print(fam[1:3]) # start is inclusive, end is exclusive
print(fam[:3])
print(fam[2:])

1.73
1.89
[1.68, 1.71]
[1.73, 1.68, 1.71]
[1.71, 1.89]


In [20]:
### TO DO ###
'''
Print out the area of the living room from the mixed data type list "areas_mixed".
Using a combination of list subsetting and variable assignment, create a new variable called 
"eat_sleep_area" that contains the sum of the area of the kitchen and the area of the bedroom.
Print the variable "eat_sleep_area".
Use slicing to create a list called "downstairs" that contains the first 6 elements of areas.
Simplify slicing by omitting the begin index.
Print the list called "downstairs".
Subset list of lists by retrieving just the area of the kitchen of the nested list.
'''

### SOLUTION ###
print(areas_mixed[5])
eat_sleep_area = (areas_mixed[3] + areas_mixed[-3])
print(eat_sleep_area)
downstairs = areas[:6]
print(downstairs)
print(house[1][1])

20.0
28.75
[11.25, 18.0, 20.0, 10.75, 9.5]
18.0


In [21]:
# Manipulating lists
# Change list elements
print(fam)
fam[2] = 1.87
print(fam, "\n")
print(fam2)
fam2[0:2] = ["liz", 1.72]
print(fam2, "\n")

# Add list elements
fam_ext = fam2 + ["me", 1.79]
print(fam_ext, "\n")

# Remove list elements
del(fam[2])
print(fam)

[1.73, 1.68, 1.71, 1.89]
[1.73, 1.68, 1.87, 1.89] 

[['liz', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]
['liz', 1.72, ['mom', 1.71], ['dad', 1.89]] 

['liz', 1.72, ['mom', 1.71], ['dad', 1.89], 'me', 1.79] 

[1.73, 1.68, 1.89]


In [22]:
# Behind the scenes
x = ["a", "b", "c"]
y = x # copy reference to list, not actual values; in terms of computer memory it is the same
y[1] = "z"
print(y)
print(x, "\n")

x = ["a", "b", "c"]
y = list(x)
y[1] = "z"
print(y)
print(x, "\n")

y = x[:]
y[1] = "z"
print(y)
print(x)

['a', 'z', 'c']
['a', 'z', 'c'] 

['a', 'z', 'c']
['a', 'b', 'c'] 

['a', 'z', 'c']
['a', 'b', 'c']


In [24]:
## TO DO ##
'''
Update the area of the bathroom in your list "areas_mixed" to be 10.50.
Change the string "living room" to "chill zone" in "areas_mixed".
Print the list "areas_mixed".
Add a poolhouse (24.5) and garage (15.45) to your "areas_mixed" list and store the resulting 
list as "areas_mixed_new".
Print the list "areas_mixed_new"
Delete the poolhouse and corresponding area from the list areas_new.
Print the list "areas_mixed_new".
'''

### SOLUTION ###
areas_mixed[-1] = 10.50
areas_mixed[4] = "chill zone"
print(areas_mixed)
areas_mixed_new = areas_mixed + ["poolhouse", 24.5, "garage", 15.45]
print(areas_mixed_new)
del(areas_mixed_new[-4:-2])
print(areas_mixed_new)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


## Functions

- Noting new, e.g. type()
- Piece of reusable code
- Solves particular task
- Leverage functions instead of writing custom code

In [25]:
tallest = max(fam) # logic is abstracted
print(tallest)

1.89


In [26]:
# Multiple arguments
print(round(1.68, 1))
print(round(1.68)) # default arguments

1.7
2


In [27]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



Leverage existing functions to get work done!
- standard task -> function probably exists
- internet is your friend

In [28]:
## TO DO ##
'''
Print the length of the fam list.
Find out what the function pow() is doing.
Find out how the function sorted() works.
Reverse the number list defined below and print the result.
'''

numbers = [11.25, 18.0, 20.0, 25.0]

### SOLUTION ###
print(len(fam))
help(pow)
help(sorted)
print(sorted(numbers, reverse=True))

3
Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

[25.0, 20.0, 18.0, 11.25]


## Methods

- Functions that belong to objects
- All data structures we have seen so far are objects
- Everyting = object
- Objects have methods associated, depending on type

In [29]:
# Python data structures are objects
sister = "liz" # object of type str
height = 1.73 # object of type float
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89] # object of type list

print(sister.capitalize()) # "Call method capitalize() on sister"
print(sister.replace("z", "sa"))
print(fam.index("mom")) # "Call method index() on fam"
print(fam.count(1.73))

Liz
lisa
4
1


In [30]:
print(fam.replace("mom", "mommy")) # list object has no method "replace"

AttributeError: 'list' object has no attribute 'replace'

In [31]:
# Method can be different depending on type of object
print(sister.index("z"))
print(fam.index("mom"))

2
4


In [32]:
# Some methods change the objects they are called on (others not)
fam.append("me")
print(fam)
fam.append(1.79)
print(fam)

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me']
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'me', 1.79]


In [33]:
## TO DO ##
'''
Create a variable called "place" and store the string "poolhouse" in it.
Count the number of times the letter "o" appears in the variable "place" by calling the method count
on it.
Use your "areas" list to find the index of the number 20.0.
Use the method append to add the area 15.45 to your "areas" list.
Print the "areas" list.
'''

### SOLUTION ###
place = "poolhouse"
print(place.count("o"))
print(areas.index(20.0))
areas.append(15.45)
print(areas)

3
2
[11.25, 18.0, 20.0, 10.75, 9.5, 15.45]


## Packages

- All code can't be in the general Python distribution that we have installed.
    - That would be a mess and impossible to maintain
- That is where packages come into the picture
- Think of packages as a directory of python scripts
    - Each script is a so called module
    - In the modules, functions, methods and types are defined to solve particular problems
- Thousands of packages are available
- Very prominent packages for Data Science are among others:
    - NumPy
    - Matplotlib
    - scikit-learn

In [34]:
# Import packages
import numpy as np

numbers = np.array([1, 2, 3]) # array is a function from the NumPy package

In [35]:
## TO DO ##
'''
Import the package called math.
Use the function radians to convert the angle 12 degrees into radians and print the result.
'''

### SOLUTION ###
import math
print(math.radians(12))

0.20943951023931956


## NumPy 

- One feature is missing in Lists: mathematical operations over collections at speed
- Use NumPy as an alternative for easy and fast calculations over entire arrays
- NumPy has a new data type: arrays

In [36]:
# Problem with lists
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.3, 88.4, 68.7]

In [37]:
bmi = weight / height ** 2 # this will throw an error
print(bmi)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [38]:
np_height = np.array(height) 
np_weight = np.array(weight)

In [39]:
bmi = np_weight / np_height ** 2
print(bmi)

[21.85171573 20.97505669 21.64768647 24.7473475  21.44127836]


In [40]:
# Different behavior of different Python data types
print(height + weight)
print(np_height + np_weight)

[1.73, 1.68, 1.71, 1.89, 1.79, 65.4, 59.2, 63.3, 88.4, 68.7]
[67.13 60.88 65.01 90.29 70.49]


In [41]:
# Indexing NumPy arrays
print(bmi[1])
print(bmi[bmi > 23])

20.97505668934241
[24.7473475]


In [42]:
## TO DO ##
'''
Convert the list called "baseball" into a numpy array called "np_baseball".
Print the type of "np_baseball"
Multiply each value in "np_baseball" by 2 and print the result.
Print all values of np_baseball that are below 200.
'''

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

### SOLUTION ###
np_baseball = np.array(baseball)
print(type(np_baseball))
print(np_baseball*2)
print(np_baseball[np_baseball < 200])

<class 'numpy.ndarray'>
[360 430 420 420 376 352 418 400]
[180 188 176]


In [43]:
# 2D NumPy array
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])

In [44]:
print(np_2d.shape) # shape is an attribute of np.array
print(np_2d[0][2])
print(np_2d[:, 1:3])

(2, 5)
1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]


In [45]:
# Basic statistics with NumPy
print(np_2d.mean(axis=1)) # Method of NumPy array data structure
print(np.mean(np_2d[0,:]), np.mean(np_2d[1,:])) # NumPy function
print(np.std(np_2d[0,:]))
print(np.corrcoef(np_2d[0,:]))

[ 1.76 69.06]
1.7600000000000002 69.06
0.07429670248402682
1.0


Well done! You are now a Pythonista :)

As a last remark, [Datacamp](https://www.datacamp.com) is a really great resource to learn coding skills relevant for Data Science.
We can also really recommend the articles and tutorials from [Real Python](https://realpython.com/tutorials/basics/) (albeit less Data Science specific).